# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - oraclejdk8

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту rishakhanov@rambler.ru если сборка упала
notifications:
  email:
    recipients:
      -rishakhanov@rambler.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="adaaee4e-5154-4d4b-b9f5-64895040a2de"